### PR TITLE
run of pre-commit to apply changes

### PR DESCRIPTION
**Pull request by McKnight-42**
to be merged into #22 to break up the pr

ran post changes and created a "adapter" scaffold start to run pre-commit against https://github.com/McKnight-42/dbt-testone
Screen Shot 2022-04-12 at 12 19 15 PM

ran locally all but some flake8 imports for things users will need but not used at initialization of scaffold.

### CODE REVIEW

**Comment by McKnight-42** [comment]
when running against the sub directory of this repo we get errors caused by the name of the cookiecutter string
Screen Shot 2022-04-12 at 12 21 36 PM
s

**Comment by kwigley** [comment]
> when running against the sub directory of this repo we get errors caused by the name of the cookiecutter string Screen Shot 2022-04-12 at 12 21 36 PM 

@McKnight-42 I think `black` only parses valid Python code, Jinja templating isn't valid Python code. Which is fine, I don't think we need the ability to run pre-commit on the templated repo 👍

**Review by kwigley — APPROVED** [review]

**Comment by McKnight-42** [comment]
@leah any thoughts on the concurrency part of the gitub action couldn't find a pointer it seemed to like for self testing in `{{cookiecutter.project_name}}/.github/workflows/main.yml`

**Comment by ChenyuLInx** [comment]
> @leah any thoughts on the concurrency part of the gitub action couldn't find a pointer it seemed to like for self testing in `{{cookiecutter.project_name}}/.github/workflows/main.yml`

Synced with Matt and we figured out all we need to do is add 
>   "_copy_without_render": [
      "**/main.yml"
  ]

to `cookiecutter.json` to not render the file.

**Review by ChenyuLInx — APPROVED** [review]
Adding the `_copy_without_render ` then I think we are good to go!

**Pull request merged**
