### PR TITLE
Pre-commit without running

### PR DESCRIPTION
**Pull request by McKnight-42**
reopening #22 as it was merged to early.

### CODE REVIEW

**Comment by McKnight-42** [comment]
as a progress note of where generated projects sit https://github.com/McKnight-42/dbt-testadapter/pull/1 have the first gha for code-quality running and passing, still need to get the "build" ones to pass.

**Comment by McKnight-42** [comment]
@jtcohen6 was wondering if you had any final thoughts on the [project_version](https://github.com/dbt-labs/dbt-database-adapter-scaffold/blob/main/cookiecutter.json#L10) for the plugins?

**Comment by jtcohen6** [comment]
@McKnight-42 Good call! I think `dbt_version` (core version) and `project_version` could be combined into one, and they should both be `1.x.0`, where `x` is the latest minor version of `dbt-core`.

For now, that means `1.0.0`. Very soon (next few weeks), it should bump to `1.1.0`.

Should that still be user input with a sensible default, or something that we enforce?

**Comment by McKnight-42** [comment]
> @McKnight-42 Good call! I just took a quick look through where `dbt_version` and `project_version` are being used. They seem interchangeable, and I think we could combine them into one.
> 
> That combined value should always be `1.x.0`, where `x` is the latest minor version of `dbt-core`. For now, that means `1.0.0`. Very soon (next few weeks), it should bump to `1.1.0`.
> 
> Questions:
> 
> * Should that still be user input with a sensible default, or something that we enforce?
> * How do we want to automate that version bump, if this scaffold lives outside the `dbt-core` repo? We could make it part of our minor  version release process, which coordinates across core + plugins

Me and @kwigley worked on creating this https://github.com/dbt-labs/dbt-database-adapter-scaffold/pull/25 which should help us stay in step on for at least initial install and offer users chance to change dbt-version if for some reason they are using a different version than latest that would be out of step.

**Comment by ChenyuLInx** [comment]
@jtcohen6 One concern I have over our current `project_version` is that we default it to match the `dbt-core` version, so for all new adapters, they are versioned to `1.0+` even though this might be the first version of it that hasn't been fully tested. Usually, the default first version is `0.1.0`. We do this to make sure it is compatible with the `dbt-core` version with makes sense. But I am wondering should we emphasize that somewhere in README that `1.0+` for the adapter version might still not be a stable version assuming people's default thought would be it is.

**Review by ChenyuLInx — APPROVED** [review]
This looks great!! Tested and run locally and the generated project looks great with more detailed instruction for function/macros. We don't have to wait for the project version question.

**Comment by jtcohen6** [comment]
@ChenyuLInx It's a really good question, and I'm curious what other projects with similar plugin patterns have done in this case.

My two quick thoughts:
- I think we should insist on this convention for "validated" adapters, so that end users have consistency around breaking changes, deprecations, etc. We shouldn't include an adapter in dbt Cloud, for instance, that differs from this convention.
- I also think there are other ways of signalling plugin maturity — GitHub stars, # of users, etc.

**Pull request merged**
